'use client'
// src/app/layout.js
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Real state",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const isAuthRoute = pathname.startsWith("/auth") || pathname.startsWith("/auth/superadmindashboard");


  return (
    <html lang="en">
      <body className={inter.className}>
        {!isAuthRoute && <Header />}
        {children}
        {!isAuthRoute && <Footer />}
      </body>
    </html>
  );
}
